apiVersion: v1
kind: Service
metadata:
    name: sentimental-analysis-service
    namespace: sentimental-analysis
spec:
    ports:
        - name: http
          port: 8000
          targetPort: {{ .Values.image.containerPort }}
    selector:
        app: sentimental-analysis-pod